services:
  - type: web
    name: coinbot
    runtime: python
    plan: free
    repo: https://github.com/charliescustomsandrepair-star/investment-tools
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: HEADLESS
        value: "true"

  - type: web
    name: airfarm
    runtime: python
    plan: free
    repo: https://github.com/charliescustomsandrepair-star/investment-tools
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: HEADLESS
        value: "true"
